//
// TaskListCellModel.cs
//
// Author:
// 	Jim Borden  <jim.borden@couchbase.com>
//
// Copyright (c) 2016 Couchbase, Inc All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Input;

using Acr.UserDialogs;
using Couchbase.Lite;
using Robo.Mvvm.Input;
using Robo.Mvvm.Services;
using Training.Core;
using Training.Models;

namespace Training.ViewModels
{
   
    /// <summary>
    /// The view model for an entry in the TaskListsPage table view
    /// </summary>
    public sealed class TaskListCellModel : BaseNavigationViewModel<TaskListModel>
    {
        #region Properties

        ObservableConcurrentDictionary<string, TaskListCellModel> _taskLists;
        public ObservableConcurrentDictionary<string, TaskListCellModel> TaskLists
        {
            get => _taskLists;
            set => SetPropertyChanged(ref _taskLists, value);
        }

        /// <summary>
        /// Gets the document ID of the document being tracked
        /// </summary>
        public string DocumentID { get; set; }

        /// <summary>
        /// Gets the handler for an edit request
        /// </summary>
        public ICommand EditCommand => new Command(async() => await Edit());

        /// <summary>
        /// Gets the handler for a delete request
        /// </summary>
        public ICommand DeleteCommand => new Command(() => Delete());

        /// <summary>
        /// Gets or sets the incomplete count for this row
        /// </summary>
        public int IncompleteCount 
        {
            get => _incompleteCount;
            set => SetPropertyChanged(ref _incompleteCount, value);
        }
        private int _incompleteCount;

        /// <summary>
        /// Gets or sets the name of the list
        /// </summary>
        public string Name
        {
            get => _name;
            set => SetPropertyChanged(ref _name, value);
        }
        string _name = "";

        #endregion

        #region Constructors

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="documentId">The ID of the document to track.</param>
        /// <param name="name">The name generated by the view</param>
        public TaskListCellModel(INavigationService navigation, IUserDialogs dialogs, 
            string documentId, string name, ObservableConcurrentDictionary<string, TaskListCellModel> taskLists) 
            : base(navigation, dialogs, new TaskListModel(documentId))
        {
            Navigation = navigation;
            Dialogs = dialogs;
            TaskLists = taskLists;
            DocumentID = documentId;
            _incompleteCount = 0;
            Name = name;
        }

        #endregion

        #region Private API

        private void Delete()
        {
            try {
                if (!Model.Delete()) {
                    Dialogs.Toast("Error: Missing delete access");
                }
            } catch(Exception e) {
                Dialogs.Toast(e.Message);
            }
            TaskLists.Remove(DocumentID);
        }

        private async Task Edit()
        {
            var result = await Dialogs.PromptAsync(new PromptConfig {
                Title = "Edit Task List",
                Text = Name,
                Placeholder = "List Name"
            });

            if(result.Ok) {
                try {
                    Name = Model.Edit(result.Text);
                } catch (Exception e) {
                    Dialogs.Toast(e.Message);
                }
            }
        }

        #endregion

        #region Overrides

        public override bool Equals(object obj)
        {
            var other = obj as TaskListCellModel;
            if(other == null) {
                return false;
            }

            return DocumentID.Equals(other.DocumentID) && Name.Equals(other.Name) && IncompleteCount == other.IncompleteCount;
        }

        public override int GetHashCode()
        {
            return DocumentID.GetHashCode() ^ (Name ?? "").GetHashCode() ^ IncompleteCount.GetHashCode();
        }

        #endregion

        public void Dispose()
        {
            Model = null;
        }

    }
}

