
Vagrant.configure(2) do |config|

  host_ip = {
    "couchbase-server" => "192.168.34.11",
    "sync-gateway1" => "192.168.34.12",
    "sync-gateway2" => "192.168.34.13",
    "nginx" => "192.168.34.14",    
    "sync-gateway3" => "192.168.34.15",    
  }
  
  host_ip.each do |host_name, ip|
      config.vm.define host_name do |host|
        host.vm.box = "couchbase-mobile-training"
        host.vm.hostname = host_name
        host.vm.network "private_network", ip: ip
        host.vm.synced_folder ".", "/tmp/sync", disabled: true
        host.vm.provider "virtualbox" do |vb|
            # Customize the amount of memory on the VM:
            vb.memory = "2048"

            # Allow vm to send data via VPN
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
      end
  end

end
